name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
defaults:
  run:
    shell: bash
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v5
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install Python requirements
        run: |
          pip install --no-deps -r requirements.txt
      - name: Generate Python API client
        run: |
          ./generate_python_client.sh
      - name: Check code style with Ruff
        run: |
          ruff check tests/
      - name: Typecheck code
        run: |
          mypy tests/*.py
      # - name: Run tests
      #   rune: |
      #     pytest

  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v5
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install Prettier
        run: |
          npm ci prettier
      - name: Install Ruff
        run: |
          pip install ruff -c requirements.txt
      - name: Format code
        run: |
          .tools/reformat.sh
      - name: Check if any edits are necessary
        run: |
          git diff --color --exit-code
      - name: Apply automatic fixes using pre-commit-ci-lite
        if: failure() && github.event_name == 'pull_request'
        uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
